# vim: set expandtab shiftwidth=2 tabstop=8 textwidth=0:
libinput_references:
  default_settings: &default_settings
    working_directory: ~/libinput
  build_and_test: &build_and_test
    run:
      name: Build
      command: |
        meson build --prefix=/opt/libinput
        mesonconf build
        ninja -v -C build
  install: &install
    run:
      name: Installing
      command: ninja -v -C build install
  export_logs: &export_logs
    store_artifacts:
      path: ~/libinput/build/meson-logs

fedora_settings: &fedora_settings
  <<: *default_settings
  steps:
    - run: 
        name: Install prerequisites
        command: dnf install -y git gcc gcc-c++ meson check-devel libudev-devel libevdev-devel doxygen graphviz valgrind binutils libwacom-devel cairo-devel gtk3-devel glib2-devel mtdev-devel
    - checkout
    - *build_and_test
    - *install
    - *export_logs

version: 2
jobs:
  fedora_latest:
    <<: *fedora_settings
    docker:
      - image: fedora:latest

workflows:
  version: 2
  compile:
    jobs:
      - fedora_latest
